from generalfile import Path
from generallibrary import join_with_str
from generalimport import generalimport, get_installed_packages
# generalimport("foobar")



import sys
import os
import pkgutil
import importlib
import collections


x = get_installed_packages()
y1 = set(sys.builtin_module_names)
y2 = {module.name for module in pkgutil.iter_modules()}
z = {
"aiohttp",
"aiosignal",
"alpha-vantage",
"altgraph",
"appdirs",
"asgiref",
"async-generator",
"async-timeout",
"atari-py",
"atomicwrites",
"attrs",
"bleach",
"cachetools",
"cattrs",
"certifi",
"cffi",
"cfgv",
"chardet",
"charset-normalizer",
"click",
"cloudpickle",
"colorama",
"configparser",
"coverage",
"crayons",
"cryptography",
"cycler",
"defusedxml",
"Deprecated",
"dill",
"distlib",
"Django",
"djangorestframework",
"docutils",
"exchange-calendars",
"filelock",
"Flask",
"frozenlist",
"ftfy",
"future",
"generalbrowser",
"generaldunder",
"generalfile",
"generalgui",
"generalimport",
"generallibrary",
"generalmainframe",
"generalpackager",
"generalvector",
"gitdb",
"GitPython",
"google-auth",
"graphics.py",
"graphviz",
"gym",
"gym-notices",
"h11",
"identify",
"idna",
"importlib-metadata",
"iniconfig",
"itsdangerous",
"Jinja2",
"jira",
"joblib",
"Js2Py",
"jsonpickle",
"keyboard",
"keyring",
"kiwisolver",
"korean-lunar-calendar",
"llvmlite",
"lxml",
"mailchecker",
"MarkupSafe",
"matplotlib",
"MouseInfo",
"multidict",
"multitasking",
"networkx",
"nltk",
"nodeenv",
"numba",
"numpy",
"oauthlib",
"opencv-python",
"outcome",
"packaging",
"pandas",
"pandas-market-calendars",
"patsy",
"pefile",
"phonenumbers",
"Pillow",
"pip",
"pkginfo",
"platformdirs",
"pluggy",
"progress",
"psutil",
"ptan",
"py",
"pyasn1",
"pyasn1-modules",
"PyAutoGUI",
"pycparser",
"PyGetWindow",
"PyGithub",
"Pygments",
"pyinstaller",
"pyinstaller-hooks-contrib",
"pyjsparser",
"PyJWT",
"pyluach",
"PyMsgBox",
"PyNaCl",
"pyOpenSSL",
"pyparsing",
"pyperclip",
"PyRect",
"PyScreeze",
"pytesseract",
"pytest",
"python-benedict",
"python-dateutil",
"python-dotenv",
"python-fsutil",
"python-slugify",
"pytweening",
"pytz",
"pytz-deprecation-shim",
"pywin32",
"pywin32-ctypes",
"PyYAML",
"readme-renderer",
"regex",
"requests",
"requests-oauthlib",
"requests-toolbelt",
"rfc3986",
"rsa",
"scikit-learn",
"scipy",
"selenium",
"Send2Trash",
"setuptools",
"six",
"smmap",
"snakeviz",
"sniffio",
"sortedcontainers",
"sqlparse",
"StackAPI",
"statsmodels",
"tabulate",
"text-unidecode",
"threadpoolctl",
"toml",
"tomli",
"toolz",
"torch",
"tornado",
"tqdm",
"trio",
"trio-websocket",
"twilio",
"twine",
"typing-extensions",
"tzdata",
"tzlocal",
"urllib3",
"virtualenv",
"wcwidth",
"webdriver-manager",
"webencodings",
"Werkzeug",
"wheel",
"wrapt",
"wsproto",
"xmltodict",
"yarl",
"yfinance",
"zipp",}  # pip list

all_ = x | y1 | y2 | z

print(len(all_))

lines = ["module, working_set, builtin_module_names, iter_modules, pip list, all lower"]

for module in all_:
    lines.append(join_with_str(",", [
        module,
        module in x,
        module in y1,
        module in y2,
        module in z,
        module.lower() == module,
    ]))

Path("data.csv").text.write("\n".join(lines), overwrite=True)

