name: WorkflowDev

on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
    branches-ignore:
      - master
      - main

defaults:
  run:
    working-directory: ../../main

jobs:
  unittest:
    if: contains(github.event.head_commit.message, '[CI SKIP]') == false && contains(github.event.head_commit.message, '[CI AUTO]') == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Create folder
        working-directory: ../../
        run: mkdir main
      - name: Set up Git SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GIT_SSH }}
      - name: Set up python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install necessities
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine
      - name: Clone 6 repos
        run: |
          mkdir repos
          cd repos
          git clone ssh://git@github.com/ManderaGeneral/generalimport.git -b ${{ github.ref_name }}
          git clone ssh://git@github.com/ManderaGeneral/generaltool.git
          git clone ssh://git@github.com/ManderaGeneral/generallibrary.git
          git clone ssh://git@github.com/ManderaGeneral/generalfile.git
          git clone ssh://git@github.com/ManderaGeneral/generalvector.git
          git clone ssh://git@github.com/ManderaGeneral/generalpackager.git
      - name: Install 6 repos
        run: |
          cd repos
          pip install -e generalimport[full]
          pip install -e generaltool[full]
          pip install -e generallibrary[full]
          pip install -e generalfile[full]
          pip install -e generalvector[full]
          pip install -e generalpackager[full]
      - name: Run Packager method 'workflow_unittest'
        run: |
          cd repos
          python -c "from generalpackager import Packager; Packager().workflow_unittest()"

