name: WorkflowDev

on:
  push:
    branches-ignore:
      - master
      - main

defaults:
  run:
    working-directory: ../../main

jobs:
  unittest:
    if: contains(github.event.head_commit.message, '[CI SKIP]') == false && contains(github.event.head_commit.message, '[CI AUTO]') == false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Create folder
        working-directory: ../../
        run: mkdir main
      - name: Set up python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install necessities
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine
      - name: Clone
        run: |
          mkdir repos
          cd repos
          git clone https://github.com/${{ github.repository }}.git -b ${{ github.ref_name }}
      - name: Install
        run: |
          cd repos/generalimport
          pip install .[full]
      - name: Unittest
        run: |
          python -m unittest discover repos/generalimport/generalimport/test
